{"classFile":"ExceptionContextTest","className":"ExceptionContextTest","packages":"org.apache.commons.math.exception.util","methodInfos":[{"md5":"xM1Omb+VGWmnsZa6fHw9tw==","methodName":"testMessageChain","parameters":"[]"},{"md5":"hhyQQ3tFwbYjbqXPkykjXg==","methodName":"testNoArgAddMessage","parameters":"[]"},{"md5":"5E7YivCFSktPUIvtBANXLw==","methodName":"testContext","parameters":"[]"},{"md5":"XN4wbqTyCLO9dtE7mWX7yg==","methodName":"testSerialize","parameters":"[]"},{"md5":"LIj1lhLoXB50lTjMkMTgiA==","methodName":"testSerializeUnserializable","parameters":"[]"}],"addLines":[38,53,60,85,105],"delLines":[38,53,60,85,105],"type":"MODIFY","path":"src/test/java/org/apache/commons/math/exception/util/ExceptionContextTest.java","pro_Commit":"d696293435c04a8948c873fee4ed3a23536d7a26","pro_Date":"2011-09-04 22:38:40","sha1":"7924ae4cf7438b84c7b7347c7a42cc2fab0efd4d","file_Date":"2011-09-04 22:38:40","projectName":"commons-math","commitID":"d696293435c04a8948c873fee4ed3a23536d7a26"}