{"repository":"commons-math","prod_path":"src/main/java/org/apache/commons/math/exception/MathRuntimeException.java","test_path":"src/test/java/org/apache/commons/math/exception/MathRuntimeExceptionTest.java","prod_time":"2011-03-28 05:51:31","test_time":"2011-07-13 23:28:21","add_annotation_line":0,"add_call_line":14,"add_classname_line":0,"add_condition_line":1,"add_field_line":2,"add_import_line":0,"add_packageid_line":0,"add_parameter_line":0,"add_return_line":0,"del_annotation_line":0,"del_call_line":11,"del_classname_line":0,"del_condition_line":0,"del_field_line":2,"del_import_line":1,"del_packageid_line":0,"del_parameter_line":0,"del_return_line":0,"label":"NEGATIVE","pro_Commit":"e1852db1cffa808714be88c48d7d23b048e9f76f","test_Commit":"9af50ca82c8994990992696e17beeb7956cdfd89","true_label":null}