{"repository":"commons-math","prod_path":"src/main/java/org/apache/commons/math/exception/MathRuntimeException.java","test_path":"src/test/java/org/apache/commons/math/exception/MathRuntimeExceptionTest.java","prod_time":"2011-03-15 19:42:23","test_time":"2011-03-15 19:42:23","add_annotation_line":0,"add_call_line":1,"add_classname_line":0,"add_condition_line":0,"add_field_line":0,"add_import_line":0,"add_packageid_line":0,"add_parameter_line":1,"add_return_line":0,"del_annotation_line":0,"del_call_line":0,"del_classname_line":0,"del_condition_line":0,"del_field_line":0,"del_import_line":0,"del_packageid_line":0,"del_parameter_line":0,"del_return_line":0,"label":"POSITIVE","pro_Commit":"35a0923edfe498c58bfb1e86099fed85fde0c353","test_Commit":"35a0923edfe498c58bfb1e86099fed85fde0c353","true_label":null}