{"classFile":"ExceptionUtilsTest","className":"ExceptionUtilsTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"oEdGHCORvJVwEQoAqMSTsA==","methodName":"setUp","parameters":"[]"},{"md5":"oHmQzCf3Ep1/spWheNhTIQ==","methodName":"tearDown","parameters":"[]"},{"md5":"sKJ+b+E4XoHn4usonN01dw==","methodName":"testGetCause_Throwable","parameters":"[]"}],"addLines":[35,52,65,76,124],"delLines":[42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java","pro_Commit":"864721d54b8b372808b098e13120abe5c22fb9b1","pro_Date":"2016-05-25 02:13:39","sha1":"0b2ce48026457cf4f0b981503ec8d651e581d47c","file_Date":"2016-05-25 02:13:39","projectName":"commons-lang","commitID":"864721d54b8b372808b098e13120abe5c22fb9b1"}