{"classFile":"ExceptionUtilsTest","className":"ExceptionUtilsTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"wuQWcy5cVseMegwrNmglbA==","methodName":"testPrintRootCauseStackTrace_ThrowableStream","parameters":"[]"},{"md5":"GiaFDvu/RRsh1yfsFNya2Q==","methodName":"testPrintRootCauseStackTrace_ThrowableWriter","parameters":"[]"},{"md5":"RpHxZB+Fi64XBnCwaVRUxg==","methodName":"testGetRootCauseStackTrace_Throwable","parameters":"[]"}],"addLines":[391,392,417,418,433,434],"delLines":[391,392,417,418,433,434],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java","pro_Commit":"5292526e476ffbb19c6613a98464054236c86ace","pro_Date":"2013-01-22 15:09:45","sha1":"bdff2845dd9fd2b893c7d3c1452dd9e420975abb","file_Date":"2013-10-19 01:21:23","projectName":"commons-lang","commitID":"58a749fbac210527bb05448b90a07c9ce4e11c61"}