{"classFile":"ExceptionUtilsTest","className":"ExceptionUtilsTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"g1Kv6X1hOczNeoNIneJ85g==","methodName":"testConstructor","parameters":"[]"},{"md5":"cr1QkdvK5ajmOC/mxYB1bA==","methodName":"testGetRootCauseStackTrace_Throwable","parameters":"[]"}],"addLines":[111,112,113,442,452],"delLines":[111,112,113,442,452],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java","pro_Commit":"204346f7544640a8c4b97677aca0d00ccd79b12e","pro_Date":"2012-03-12 01:55:29","sha1":"5ef8ebb4e023116b0c73e042698cbe616d33144a","file_Date":"2012-09-19 09:29:22","projectName":"commons-lang","commitID":"abecd96359e5cead38d0932cec44394d68b9c6c5"}