{"classFile":"ExceptionUtilsTest","className":"ExceptionUtilsTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"di2tO8FyqPSYNlSKD9D5SA==","methodName":"testPrintRootCauseStackTrace_ThrowableStream","parameters":"[]"},{"md5":"iEIQVqjrWuaEfz7iz8YyGA==","methodName":"testPrintRootCauseStackTrace_ThrowableWriter","parameters":"[]"}],"addLines":[524,548],"delLines":[524,548],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java","pro_Commit":"ba607f525b842661d40195d0d4778528e2384e70","pro_Date":"2020-03-07 00:08:22","sha1":"28650568bca64e503031d624746e40a6c9d784fc","file_Date":"2020-03-07 00:08:22","projectName":"commons-lang","commitID":"ba607f525b842661d40195d0d4778528e2384e70"}