{"classFile":"ExceptionUtilsTest","className":"ExceptionUtilsTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"Vnle9DbBqPfMYkPbVep39Q==","methodName":"testGetRootCause_Throwable","parameters":"[]"}],"addLines":[150,153],"delLines":[150,153],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java","pro_Commit":"60412131f3679b720bcaaaf3dea4be666cefea7a","pro_Date":"2018-02-11 21:19:56","sha1":"0af68a8fbc6f749989393bf5c6c50edfb4140784","file_Date":"2018-02-11 21:19:56","projectName":"commons-lang","commitID":"60412131f3679b720bcaaaf3dea4be666cefea7a"}