{"classFile":"ExceptionUtilsTest","className":"ExceptionUtilsTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"1F4KamYV9SA1JtYUyX+PvQ==","methodName":"testPrintRootCauseStackTrace_ThrowableStream","parameters":"[]"},{"md5":"cRlfNKGcWE5zKz2CqKA/fw==","methodName":"testPrintRootCauseStackTrace_ThrowableWriter","parameters":"[]"}],"addLines":[391,396,417,422],"delLines":[391,396,417,422],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java","pro_Commit":"ff6b0ada72106d67aef1ee21d51bacac2f3af7ac","pro_Date":"2017-04-20 03:07:05","sha1":"7a4cf9d4418b3de251d710f81e67c90ab1007e97","file_Date":"2017-04-23 04:18:16","projectName":"commons-lang","commitID":"d5be24a12668a94712247d31f06ef7d416b8118c"}