{"classFile":"CloneFailedExceptionTest","className":"CloneFailedExceptionTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"IwO9+1t9hJfgBj/0v0N6Jw==","methodName":"testThrowingInformativeException","parameters":"[]"},{"md5":"/FEds3OxJgmeDG7FfrRYXA==","methodName":"testThrowingExceptionWithMessage","parameters":"[]"},{"md5":"N55PYS1RIHh2RW9wlTbrPw==","methodName":"testThrowingExceptionWithCause","parameters":"[]"},{"md5":"v0zB6sJbFlJEz8EqvciQhg==","methodName":"testWithCauseAndMessage","parameters":"[]"},{"md5":"UpAiFTXgU9zXBI9zpBmxAA==","methodName":"testWithoutCause","parameters":"[]"},{"md5":"ALj/GooB0YmPJ8toTJs54A==","methodName":"testWithoutMessage","parameters":"[]"}],"addLines":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76],"delLines":[],"type":"ADD","path":"src/test/java/org/apache/commons/lang3/exception/CloneFailedExceptionTest.java","pro_Commit":"7b6ab58a018b5f6608ea07bc414d3f34a576c6a2","pro_Date":"2010-02-11 07:22:05","sha1":"52735756a704210dcc389699db0bbf8e634678a5","file_Date":"2017-01-06 03:53:01","projectName":"commons-lang","commitID":"e8d861359ade336badcac3211e5aa447097479a6"}