{"classFile":"MathRuntimeExceptionTest","className":"MathRuntimeExceptionTest","packages":"org.apache.commons.math.exception","methodInfos":[{"md5":"TeThHdZ1E773rtzep3imVw==","methodName":"testMessageChain","parameters":"[]"},{"md5":"Z0I8OplZXSqFCIzo3sZIBg==","methodName":"testContext","parameters":"[]"}],"addLines":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78],"delLines":[],"type":"ADD","path":"src/test/java/org/apache/commons/math/exception/MathRuntimeExceptionTest.java","pro_Commit":"da462abca016b80ce42e4cb3523e3eb3522a559f","label":null,"predict":null,"commitID":"da462abca016b80ce42e4cb3523e3eb3522a559f","pro_Date":"2011-03-07 18:37:52","file_Date":"2011-03-07 18:37:52","projectName":"commons-math","sha1":"ae14f980f90382456f776af55ee6cc4d88572d1c","pro_Path":null}